name: Cloudflare-Pages-Cleanup

on:
  schedule:
    - cron: '3 3 3 * *' # 每月 3 号 UTC 3:03
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate Matrix
        id: set-matrix
        run: |
          # 直接从 GitHub Variable 读取并输出给 cleanup job
          PROJECTS='${{ vars.CF_PAGES_PROJECT_NAMES }}'
          echo "matrix=$PROJECTS" >> $GITHUB_OUTPUT

  sync:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.setup.outputs.matrix) }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --prefer-offline --no-frozen-lockfile

      - name: Run cleanup script
        run: pnpm start
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_PAGES_PROJECT_NAME: ${{ matrix.project }}
          CF_DELETE_ALIASED_DEPLOYMENTS: ${{ vars.CF_DELETE_ALIASED_DEPLOYMENTS }}

  keep-alive:
    needs: sync
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Write Log and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 切换到孤立的 logs 分支 (覆盖方式)
          git checkout --orphan logs
          
          # 清除文件并写入最新日志
          git rm -rf .
          echo "Last Run: $(date -u)" > last_run.log
          
          # 提交并强制推送以覆盖 logs 分支
          git add last_run.log
          git commit -m "chore: update logs [skip ci]"
          git push origin logs --force
